# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.18.1'

#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [4]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
a = np.zeros(10)
a[4]+=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
v = np.arange(10,49)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
v[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.random.randint(8, size = (3,3))

array([[7, 7, 6],
       [1, 4, 6],
       [0, 2, 7]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
a = np.array([1,2,0,0,4,0])
np.where(a>0)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
np.random.random((3,3,3))

array([[[0.38824518, 0.559126  , 0.76238464],
        [0.20760324, 0.46855156, 0.23362416],
        [0.72775326, 0.20976852, 0.86698187]],

       [[0.38272363, 0.84377759, 0.48401646],
        [0.8224573 , 0.76202021, 0.61448677],
        [0.10128653, 0.05473936, 0.28820909]],

       [[0.23442969, 0.46218329, 0.2696681 ],
        [0.84152164, 0.74932088, 0.87359282],
        [0.56884139, 0.96474606, 0.35353476]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
x = np.random.random((10,10))
print(np.max(x))
print(np.min(x))

0.9787448896649716
0.015020312130556435


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
x = np.random.random(30)
np.mean(x)

0.526670767972124

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [25]:
inside = np.ones((5,5))
inside[1:-1,1:-1] = 0
inside

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [33]:
x = np.diag(1 + np.arange(4) ,k = -1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [35]:
check = np.zeros((8,8))
check[1::2,::2] = 1
check[::2, 1::2] = 1
check

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [45]:
array = np.unravel_index(99, (6,7,8))

array

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [49]:

checker = np.tile(np.array([[0,1],[1,0]]), (4,4))
checker

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [50]:
random = np.mean((5,5))

normalized = (np.mean(random) - random)/np.std(random)

/home/ashutosh/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [51]:
d = np.dtype([("r", np.ubyte ,1),("g", np.ubyte , 1),("b", np.ubyte ,1),("a", np.ubyte,1)])

/home/ashutosh/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [52]:
a = np.random.random((5,3))
b = np.random.random((3,2))

np.dot(a,b)

array([[0.6798901 , 0.75008467],
       [0.70005232, 0.83093142],
       [0.81470347, 1.34311059],
       [0.90910876, 1.47792006],
       [0.89274157, 0.97953019]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [57]:
one_d = np.random.randint(15 , size = 10)
one_d[(3 < one_d) & (one_d < 8)] *= -1

one_d

array([-5,  8,  3, 11,  2,  9, 14, 10, 10,  3])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [61]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))





10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [62]:
a = np.random.randint(5, size = 10)
b = np.random.randint(5 , size = 10)

np.intersect1d(a,b)

array([0, 1, 2, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [65]:
A = np.random.randint(4, size = 3)
B = np.random.randint(4, size = 3)


np.add(A,B,out = B)
np.divide(A , 2, out = A)
np.multiply(A,B, out = A)
A

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [66]:
r = np.zeros((5,5))
r += np.arange(5)

print(r)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [71]:
def generator(i):
    for k in range(i):
        yield k
        
Z = np.fromiter(generator(10), dtype = np.float32)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [72]:
np.random.random(10)

array([0.22152754, 0.84279553, 0.1318769 , 0.23855263, 0.37070105,
       0.09408503, 0.20275225, 0.73190125, 0.8950997 , 0.58452764])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [73]:
np.sort(np.random.random(10))

array([0.14578556, 0.23189484, 0.3639042 , 0.380928  , 0.59860548,
       0.61723167, 0.89067959, 0.95648861, 0.95701863, 0.96923379])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [74]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [76]:
A = np.random.random(10)
B = np.random.random(10)
np.allclose(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
A.flags.writeable = False
A[2] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [82]:
cartesian = np.random.random((10,2))
X,Y = cartesian[:,0],cartesian[:,1]
R = np.sqrt(X**2 + Y**2)
theta = np.arctan2(Y,X)

polar = np.zeros((10,2))
polar[:,0], polar[:,1] = R, theta
polar

array([[0.51969341, 0.40459005],
       [1.25385696, 0.887882  ],
       [0.91267802, 0.55182872],
       [0.53406747, 0.51197923],
       [0.31117585, 0.78626197],
       [0.64719674, 0.45154655],
       [1.01303773, 1.1615199 ],
       [0.8543105 , 0.14653659],
       [0.57303175, 1.40193941],
       [0.41272944, 0.22492791]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [84]:
vector = np.random.randint(10,size = 10)
vector[np.argmax(vector)] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
X = np.random.random((5,5))
Y = np.random.random((5,5))

C = np.zeros_like(X)

C = 

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [92]:
random = 5 
vector = np.random.randint(10, size = 10)
c = vector - 5
index = np.argmin(np.abs(c))
print(vector[index],vector)


4 [7 9 1 1 2 8 4 9 3 3]


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [93]:
a = np.zeros(10, dtype = np.float32)
a.dtype = int32

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
np.ndenumerate

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [98]:

x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x**2,y**2)
mean, sigma = 0 ,1

g = np.exp(-((d- mean)**2/ (2 * sigma**2)))
g

array([[0.60653066, 0.7389913 , 0.85699689, 0.94595947, 0.99384617,
        0.99384617, 0.94595947, 0.85699689, 0.7389913 , 0.60653066],
       [0.60653066, 0.7389913 , 0.85699689, 0.94595947, 0.99384617,
        0.99384617, 0.94595947, 0.85699689, 0.7389913 , 0.60653066],
       [0.60653066, 0.7389913 , 0.85699689, 0.94595947, 0.99384617,
        0.99384617, 0.94595947, 0.85699689, 0.7389913 , 0.60653066],
       [0.60653066, 0.7389913 , 0.85699689, 0.94595947, 0.99384617,
        0.99384617, 0.94595947, 0.85699689, 0.7389913 , 0.60653066],
       [0.60653066, 0.7389913 , 0.85699689, 0.94595947, 0.99384617,
        0.99384617, 0.94595947, 0.85699689, 0.7389913 , 0.60653066],
       [0.60653066, 0.7389913 , 0.85699689, 0.94595947, 0.99384617,
        0.99384617, 0.94595947, 0.85699689, 0.7389913 , 0.60653066],
       [0.60653066, 0.7389913 , 0.85699689, 0.94595947, 0.99384617,
        0.99384617, 0.94595947, 0.85699689, 0.7389913 , 0.60653066],
       [0.60653066, 0.7389913 , 0.8569968

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [120]:

np.mean(x , axis = 1)

array([0.33333333, 2.        , 2.        ])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [119]:
x = np.random.randint(5,size = (3,3))
print(x,x - np.mean(x , axis = 1).reshape(3,1))

[[1 0 0]
 [0 2 4]
 [3 1 2]] [[ 0.66666667 -0.33333333 -0.33333333]
 [-2.          0.          2.        ]
 [ 1.         -1.          0.        ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [129]:
a = np.array([[9, 2, 3],
           [4, 5, 6],
           [7, 0, 5]])

a[a[:,1].argsort()]

array([[7, 0, 5],
       [9, 2, 3],
       [4, 5, 6]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [132]:
a = np.random.randint(5,size = (4,4,4,4))
np.sum(a, axis = (2,3))

array([[29, 34, 28, 35],
       [28, 37, 25, 36],
       [30, 35, 30, 30],
       [41, 22, 29, 26]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [137]:
x = np.random.randint(10,size = (5,5,3))
y = np.random.randint(10,size = (5,5))
x * y [:,:,None]

array([[[48, 32, 72],
        [63,  9, 45],
        [ 0,  0,  0],
        [ 0, 18,  3],
        [45, 35,  5]],

       [[ 4,  4,  1],
        [72,  8, 64],
        [18, 42, 42],
        [18,  0, 18],
        [ 8, 18, 18]],

       [[12, 24, 54],
        [72, 72, 64],
        [ 8,  6,  0],
        [54, 42, 24],
        [ 8, 12, 18]],

       [[ 7, 56, 35],
        [ 3,  6,  8],
        [40,  8, 24],
        [ 7, 56, 21],
        [ 0,  0,  8]],

       [[ 0,  8, 16],
        [ 0,  0,  0],
        [ 2,  6,  2],
        [12,  6, 24],
        [ 0,  1,  4]]])

#### 72. How to swap two rows of an array? (★★★)

In [138]:
y = np.random.randint(10,size = (5,5))


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [2]:
import numpy as np

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [6]:
bins = np.array([1, 3, 1, 1, 0, 0, 0, 1])
x = np.zeros(sum(bins))
numbers = np.arange(len(bins))
index = 0
for i,j in np.ndenumerate(numbers):
    for i in range(bins[i]):
        x[index] = j
        index +=1 

In [11]:
C = np.bincount([1,1,2,3,4,4,6])
x = np.repeat(np.arange(len(C)), C)
x

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def window(a , n):
    ret = np.cumsum(a)
    ret[n:] = ret[n:] + ret[:-n]
    

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)